import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Layout from '../components/Layout.jsx';
import { subscribe } from '../services/storage';
import { getRoom, updateRoomProgress } from '../services/roomService';
import { getCurrentRound, movePhase, moveToNextRound, revealRoundResult } from '../services/roundService';
import { calculateAllTeamResultsForRound, generateFinalResults } from '../services/calculationService';
export default function HostDashboardPage(){ const {roomId}=useParams(); const [tick,setTick]=useState(0); useEffect(()=>subscribe(()=>setTick(x=>x+1)),[]); const room=getRoom(roomId); if(!room) return <Layout><div className="card">방 정보를 찾을 수 없습니다.</div></Layout>; const round=getCurrentRound(roomId); const progress=room.roomProgress; const teams=Object.values(room.teams); const players=Object.values(room.players);
return <Layout roomId={roomId}><section className="card hero"><h2>Host Dashboard</h2><p>입장 코드: <b className="code">{room.joinCode}</b> · 참가 링크: <Link to={`/join/${room.joinCode}`}>/join/{room.joinCode}</Link></p><h3>{round?.title} · {progress.currentPhase}</h3><div className="actions"><button onClick={()=>movePhase(roomId,'prev')}>이전 단계</button><button className="primary" onClick={()=>movePhase(roomId,'next')}>다음 단계</button><button onClick={()=>moveToNextRound(roomId)}>다음 라운드</button><button onClick={()=>updateRoomProgress(roomId,{isScreenLocked:!progress.isScreenLocked})}>{progress.isScreenLocked?'잠금 해제':'화면 잠금'}</button><button onClick={()=>{calculateAllTeamResultsForRound(roomId, progress.currentRoundId); revealRoundResult(roomId);}}>계산 후 결과 공개</button><button onClick={()=>generateFinalResults(roomId)}>최종 판정 생성</button></div></section><section className="grid2"><div className="card"><h3>참가자</h3>{players.length?players.map(p=><p key={p.playerId}>{p.displayName} · {room.teams[p.teamId]?.teamName}</p>):<p className="muted">아직 입장자가 없습니다.</p>}</div><div className="card"><h3>팀 화면</h3>{teams.map(t=><p key={t.teamId}><Link to={`/team/${roomId}/${t.teamId}`}>{t.teamName} 진행 화면</Link></p>)}</div></section><section className="card"><h3>팀별 상태</h3><table><thead><tr><th>팀</th><th>최대 리스크</th><th>상태값</th></tr></thead><tbody>{teams.map(t=>{const s=room.stateValues[t.teamId];return <tr key={t.teamId}><td>{t.teamName}</td><td>{s.maxRiskLabel}</td><td>{Object.values(s.values).join(' / ')}</td></tr>})}</tbody></table></section></Layout>}
