import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Layout from '../components/Layout.jsx';
import RoundCard from '../components/RoundCard.jsx';
import ChoiceList from '../components/ChoiceList.jsx';
import ResultCard from '../components/ResultCard.jsx';
import { subscribe, readDb, updateDb } from '../services/storage';
import { getPlayer } from '../services/playerService';
import { getCurrentRound } from '../services/roundService';
import { submitVote, getVote } from '../services/voteService';
import { defaultResultCard } from '../data/seedResultCards';
export default function PlayerPage(){ const {roomId,playerId}=useParams(); const [tick,setTick]=useState(0); const [choiceId,setChoiceId]=useState(''); const [reason,setReason]=useState(''); const [msg,setMsg]=useState(''); useEffect(()=>subscribe(()=>setTick(x=>x+1)),[]); const db=readDb(); const room=db.rooms[roomId]; const player=getPlayer(roomId,playerId); const round=getCurrentRound(roomId); if(!room||!player||!round) return <Layout><div className="card">정보를 찾을 수 없습니다.</div></Layout>; const choices=db.gameContent.choices.filter(c=>round.choiceIds.includes(c.choiceId)).sort((a,b)=>a.displayOrder-b.displayOrder); const vote=getVote(roomId,round.roundId,player.teamId,playerId); const canVote=room.roomProgress.currentPhase==='playerVote'&&!room.roomProgress.isScreenLocked; const calculation=room.roundCalculations[`${round.roundId}_${player.teamId}`]; const resultCard=db.gameContent.resultCards[calculation?.resultCardId]||defaultResultCard;
const save=()=>{try{submitVote({roomId, roundId:round.roundId, teamId:player.teamId, playerId, choiceId:choiceId||vote?.choiceId, reason:reason||vote?.reason}); setMsg('개인 선택을 저장했습니다.')}catch(e){setMsg(e.message)}};
const saveReflection=()=>{updateDb(db2=>{const d=db2.rooms[roomId].declarations[player.teamId]||{teamId:player.teamId,individualReflections:{}}; d.individualReflections={...(d.individualReflections||{}),[playerId]:{habit:reason,nextBehavior:'다음 현업에서 선택의 대가를 먼저 확인하겠습니다.',submittedAt:Date.now()}}; db2.rooms[roomId].declarations[player.teamId]=d;});setMsg('개인 성찰을 저장했습니다.')};
return <Layout roomId={roomId}><RoundCard round={round}/><section className="card"><p>참가자: <b>{player.displayName}</b> · 팀: <Link to={`/team/${roomId}/${player.teamId}`}>{room.teams[player.teamId].teamName}</Link></p><p className="muted">현재 단계: {room.roomProgress.currentPhase}</p>{msg&&<div className="notice">{msg}</div>}{choices.length>0 ? <><ChoiceList choices={choices} selectedChoiceId={choiceId||vote?.choiceId} onSelect={setChoiceId} disabled={!canVote}/><label>선택 이유<textarea disabled={!canVote} value={reason||vote?.reason||''} onChange={e=>setReason(e.target.value)} placeholder="왜 이 선택을 하셨습니까?"/></label><button className="primary" disabled={!canVote} onClick={save}>개인 선택 저장</button></> : round.roundId==='week12' ? <><label>개인 성찰<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="내가 반복한 판단 습관 하나는..."/></label><button className="primary" onClick={saveReflection}>성찰 저장</button></> : <p>KSA 선택은 팀 화면에서 진행합니다.</p>}</section>{room.roomProgress.resultVisible&&calculation&&<ResultCard card={resultCard} calculation={calculation}/>}</Layout>}
