import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import Layout from '../components/Layout.jsx';
import RoundCard from '../components/RoundCard.jsx';
import ChoiceList from '../components/ChoiceList.jsx';
import KsaSelector from '../components/KsaSelector.jsx';
import OutputForm from '../components/OutputForm.jsx';
import ResultCard from '../components/ResultCard.jsx';
import { subscribe, readDb, updateDb } from '../services/storage';
import { getCurrentRound } from '../services/roundService';
import { getTeamVotes } from '../services/voteService';
import { saveTeamKSA, submitTeamDecision, getTeamDecision } from '../services/teamService';
import { submitRoundOutput, getSubmission } from '../services/submissionService';
import { defaultResultCard } from '../data/seedResultCards';
export default function TeamPage(){ const {roomId,teamId}=useParams(); const [tick,setTick]=useState(0); const [finalChoiceId,setFinalChoiceId]=useState(''); const [summary,setSummary]=useState(''); const [msg,setMsg]=useState(''); useEffect(()=>subscribe(()=>setTick(x=>x+1)),[]); const db=readDb(); const room=db.rooms[roomId]; const round=getCurrentRound(roomId); if(!room||!round) return <Layout><div className="card">팀 정보를 찾을 수 없습니다.</div></Layout>; const team=room.teams[teamId]; const choices=db.gameContent.choices.filter(c=>round.choiceIds.includes(c.choiceId)).sort((a,b)=>a.displayOrder-b.displayOrder); const votes=getTeamVotes(roomId,round.roundId,teamId); const decision=getTeamDecision(roomId,round.roundId,teamId); const outputRequirement=db.gameContent.outputRequirements[round.outputRequirementId]; const submission=getSubmission(roomId,round.roundId,teamId); const calculation=room.roundCalculations[`${round.roundId}_${teamId}`]; const resultCard=db.gameContent.resultCards[calculation?.resultCardId]||defaultResultCard;
const canEdit=!room.roomProgress.isScreenLocked;
return <Layout roomId={roomId}><RoundCard round={round}/><section className="card"><h2>{team.teamName}</h2><p>{team.slogan}</p><p className="muted">현재 단계: {room.roomProgress.currentPhase}</p>{msg&&<div className="notice">{msg}</div>}</section>{round.roundId==='round0'&&<KsaSelector options={db.gameContent.ksaOptions[teamId]} selectedKSA={team.selectedKSA} onSubmit={(ksa)=>{try{saveTeamKSA(roomId,teamId,ksa);setMsg('KSA를 저장했습니다.')}catch(e){setMsg(e.message)}}}/>} {choices.length>0&&<section className="card"><h3>개인 선택 분포</h3>{votes.length?votes.map(v=><p key={v.voteId}>• {choices.find(c=>c.choiceId===v.choiceId)?.choiceText}<br/><small>{v.reason}</small></p>):<p className="muted">아직 개인 선택이 없습니다.</p>}<h3>팀 최종 선택</h3><ChoiceList choices={choices} selectedChoiceId={finalChoiceId||decision?.finalChoiceId} onSelect={setFinalChoiceId} disabled={!canEdit}/><label>토론 요약<textarea value={summary||decision?.discussionSummary||''} onChange={e=>setSummary(e.target.value)} /></label><button className="primary" onClick={()=>{try{submitTeamDecision({roomId,roundId:round.roundId,teamId,finalChoiceId:finalChoiceId||decision?.finalChoiceId,discussionSummary:summary||decision?.discussionSummary,submittedBy:'team'});setMsg('팀 결정을 저장했습니다.')}catch(e){setMsg(e.message)}}}>팀 결정 저장</button></section>} {choices.length>0&&<section className="card"><h3>산출물 입력</h3><OutputForm outputRequirement={outputRequirement} initialAnswers={submission?.answers} onSubmit={(answers)=>{try{submitRoundOutput({roomId,roundId:round.roundId,teamId,answers,submittedBy:'team'});setMsg('산출물을 저장했습니다.')}catch(e){setMsg(e.message)}}}/></section>}{room.roomProgress.resultVisible&&calculation&&<ResultCard card={resultCard} calculation={calculation}/>} {round.roundId==='week12'&&<section className="card"><h3>팀 선언문</h3><textarea placeholder="우리는 12주 동안..." onChange={e=>setSummary(e.target.value)} /><button className="primary" onClick={()=>{updateDb(db2=>{db2.rooms[roomId].declarations[teamId]={...(db2.rooms[roomId].declarations[teamId]||{teamId}),teamDeclaration:summary,submittedAt:Date.now()};});setMsg('팀 선언문을 저장했습니다.')}}>선언문 저장</button></section>}</Layout>}
